mysiwie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('siwieapp.urls')),
     path('accounts/', include('accounts.urls')),
]

siwieapp/urls.py
from django.urls import path
from . import views
from .views import ProfileUpdateView

urlpatterns = [
 path('', views.Index, name='index'),
 path('aboutus/', views.AboutPage, name='about'),
 path('dashboard/internship/e-logbook/', views.Dashboard, name='dashboard'),
 path('profile/internship/', views.Profile, name='profile'),
  path('profile/update/', ProfileUpdateView.as_view(), name='profile_edit'),
 path('internship/placement/detail/<intern_id>', views.Detail, name='detail'),
 path('dashboard/internship/e-logbook/detail/<logbook_id>', views.log_detail, name='log_single'),
 path('dashboard/internship/e-logbook/edit/<logbook_id>', views.Addlog_Edit, name='log_edit'),
 path('search/', views.search, name='search'),
 path('log_search/', views.log_search, name='log_search'),
 path('employersLisT_placeEMent/', views.Employers_list, name='employers_list'),
 path('internship/ondo_placement/', views.OndoSearch, name='ondo_placement'),
 path('internship/lagos_placement/', views.LagosSearch, name='lagos_placement'),
 path('internship/abuja_placement/', views.AbujaSearch, name='abuja_placement'),
 path('internship/oyo_placement/', views.OyoSearch, name='oyo_placement'),

 path('dashboard/e-logbook/add_nEWlog', views.Addlog, name='add_log'),

]


from django.conf import settings
from django.conf.urls.static import static


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siwieapp/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from .managers import UserManager
from django.db.models.signals import post_save
from django.dispatch import receiver




class User(AbstractBaseUser, PermissionsMixin):
    '''This model spells out the authorization requirements'''


    username = models.CharField(_('Username'), max_length=30, unique=True)
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    is_active = models.BooleanField(_('active'), default=True)
    is_user = models.BooleanField(_('user'), default=True)
    is_admin = models.BooleanField(_('admin'), default=False)
    is_staff = models.BooleanField(_('staff'), default=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)




class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    course_of_interest = models.CharField(max_length=225, blank=True)
    phone_no = models.CharField(max_length=14, blank=True)
    placement_addr = models.CharField(max_length=225, blank=True)
    profile_image = models.ImageField(default='he.png', upload_to='user/', null=True, blank=True)

    def __str__(self):
        return f'{self.user.username} profile'

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
   instance.profile.save()

class State(models.Model):
    name = models.CharField(max_length=224)

    def __str__(self):
        return self.name
    
class Course(models.Model):
    name = models.CharField(max_length=224)

    def __str__(self):
        return self.name
    
class Internship(models.Model):
    PAY = (
        ('Yes', 'yes'),
        ('No', 'no'),
        ('Maybe', 'maybe'),
    )

    name_of_org = models.CharField(max_length=224)
    address = models.CharField(max_length=224)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    tel = models.CharField(max_length=224)
    pay_status = models.CharField(max_length=14, null=True, choices=PAY)


    def __str__(self):
        return self.name_of_org


class Week(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Day(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Logbook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=True)
    week = models.ForeignKey(Week, on_delete=models.CASCADE)
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    log_details = models.CharField(max_length=224)
    date_posted = models.DateTimeField(auto_now_add=True)
    # log_image = models.ImageField(default='default-avatar.png', upload_to='user/', null=True, blank=True)

    def __str__(self):
        return "Week{} - Day{}".format(self.week.name[:25], self.day.name[:25])

siwieapp/views.py
from django.shortcuts import render, HttpResponseRedirect,redirect,get_object_or_404
from .models import Internship, Logbook
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .form import ProfileForm, UserForm, LogForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.contrib import messages
from django.core.paginator import Paginator

@login_required()
def Index(request):
      internship = Internship.objects.all()[3:]

      context = {'internship': internship}
      return render(request, 'index.html', context)

@login_required()
def Employers_list(request):
    internship = Internship.objects.all().order_by('-name_of_org')
    internship_paginator = Paginator(internship, 6)
    page_num = request.GET.get('page')
    page = internship_paginator.get_page(page_num)

    context = {'page': page}
    return render(request, 'employers_listpage.html', context)

def search(request):
    internship = Internship.objects.all()

    keyword = request.GET.get("keyword")
    city = request.GET.get("city")

    if keyword and city:
        query_set = internship.filter(
            Q(name_of_org__icontains=keyword) |
            Q(address__icontains=city) |
            Q(state__name__icontains= city) |
            Q(course__name__icontains=keyword)
        ).distinct()

        count = internship.filter(
            Q(name_of_org__icontains=keyword) |
            Q(address__icontains=city) |
            Q(state__name__icontains=city) |
            Q(course__name__icontains=keyword)
        ).count()

    elif keyword:
        query_set = internship.filter(
            Q(name_of_org__icontains=keyword) |
            Q(address__icontains=keyword) |
            Q(state__name__icontains=keyword) |
            Q(course__name__icontains=keyword)
        ).distinct()
        count = internship.filter(
            Q(name_of_org__icontains=keyword) |
            Q(address__icontains=keyword) |
            Q(state__name__icontains=keyword) |
            Q(course__name__icontains=keyword)
        ).count()

    elif city:
        query_set = internship.filter(

            Q(address__icontains=city) |
            Q(state__name__icontains=city)

        ).distinct()

        count = internship.filter(

            Q(address__icontains=city) |
            Q(state__name__icontains=city)

        ).count()

    else:
        query_set = internship

    context = {'internship':internship,
               'query_set':query_set,
               'keyword':keyword,
               'city':city,
               'count': count}
    return render(request, 'search_page.html', context)

def log_search(request):
    logbook = Logbook.objects.all()


    keyword = request.GET.get("keyword")
    date = request.GET.get("date")

    if keyword and date:
        query_set = logbook.filter(
            Q(log_details__icontains=keyword) |
            Q(date_posted__icontains=date)

        ).distinct()

        count = logbook.filter(
            Q(log_details__icontains=keyword) |
            Q(date_posted__icontains=date)
        ).count()

    elif keyword:
        query_set = logbook.filter(
            Q(log_details__icontains=keyword)
        ).distinct()
        count = logbook.filter(
            Q(log_details__icontains=keyword)
        ).count()

    elif date:
        query_set = logbook.filter(

            Q(date_posted__icontains=date)

        ).distinct()

        count = logbook.filter(

            Q(date_posted__icontains=date)

        ).count()

    else:
        query_set = logbook



    context = {'logbook':logbook,
               'query_set':query_set,
               'keyword':keyword,
               'date':date,
               'count': count}

    return render(request, 'logsearch.html', context)


@login_required()
def Dashboard(request):
      log_user = request.user

      logbooks = Logbook.objects.filter(user = log_user)

      log_paginator = Paginator(logbooks, 5)
      page_num = request.GET.get('page')
      page = log_paginator.get_page(page_num)

      context = {'page':page,
                 'count': log_paginator.count}
      return render(request, 'dashboard.html', context)

def log_detail(request, logbook_id):
    logbook = Logbook.objects.get(pk=logbook_id)
    context = {
        'logbook': logbook
    }
    return render(request, 'log-single.html', context)

@login_required()
def Profile(request):
      internship = Internship.objects.all()
      logbook = Logbook.objects.all()[15:]

      context = {'internship':internship,
                 'logbook':logbook}
      return render(request, 'profile.html', context)

@login_required()
def ProfileEdit(request):

      context = {}
      return render(request, 'profile-edit.html', context)


@login_required()
def Detail(request, intern_id):
    intern = Internship.objects.get(pk=intern_id)
    context = {
        'intern': intern
    }
    return render(request, 'career-single.html', context)


@login_required()
def OndoSearch(request):
    internship = Internship.objects.all()

    query_set = internship.filter(

        Q(state__name__icontains='ondo')

    ).distinct()

    count = internship.filter(

        Q(state__name__icontains='ondo')

    ).count()

    context = {'internship': internship,
               'query_set': query_set,
               'state': 'Ondo',
               'count':count}
    return render(request, 'state_searchpage.html', context)

@login_required()
def LagosSearch(request):
    internship = Internship.objects.all()

    query_set = internship.filter(

        Q(state__name__icontains='lagos')

    ).distinct()

    count = internship.filter(

        Q(state__name__icontains='lagos')

    ).count()

    context = {'internship': internship,
               'query_set': query_set,
               'state': 'Lagos',
               'count':count}
    return render(request, 'state_searchpage.html', context)

@login_required()
def AbujaSearch(request):
    internship = Internship.objects.all()

    query_set = internship.filter(

        Q(state__name__icontains='abuja')

    ).distinct()

    count = internship.filter(

        Q(state__name__icontains='abuja')

    ).count()

    context = {'internship': internship,
               'query_set': query_set,
               'state': 'Abuja',
               'count':count}
    return render(request, 'state_searchpage.html', context)

@login_required()
def OyoSearch(request):
    internship = Internship.objects.all()

    query_set = internship.filter(

        Q(state__name__icontains= 'oyo')

    ).distinct()

    count = internship.filter(

        Q(state__name__icontains='oyo')

    ).count()

    context = {'internship': internship,
               'query_set':query_set,
               'state': 'Oyo',
               'count':count}
    return render(request, 'state_searchpage.html', context)


class ProfileUpdateView(LoginRequiredMixin,TemplateView):
    user_form = UserForm
    profile_form = ProfileForm
    template_name = 'profile-edit.html'

    def post(self, request):
        post_data = request.POST or None
        file_data = request.FILES or None

        user_form = UserForm(post_data, instance=request.user)
        profile_form = ProfileForm(post_data, file_data, instance=request.user.profile)


        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,'Your profile was successfully updated')
            return HttpResponseRedirect(reverse_lazy('profile'))

        context = self.get_context_data(
            user_form=user_form,
            profile_form=profile_form
        )
        return self.render_to_response(context)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


from django.utils import timezone
@login_required()
def Addlog(request):
    now = timezone.now()
    if request.method == 'POST':
        form = LogForm(request.POST)

        if form.is_valid:
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()

            return redirect('dashboard')
    else:
        form = LogForm()
    context = {
        'form': form,
        'now': now,
    }
    return render(request, 'add_log.html', context)

def Addlog_Edit(request, logbook_id):

    logbook = get_object_or_404(Logbook, id=logbook_id)

    now = timezone.now()
    if request.method == 'POST':
        form = LogForm(request.POST, instance=logbook)

        if form.is_valid:
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()

            return redirect('dashboard')
    else:
        form = LogForm(instance=logbook)
    context = {
        'logbook': logbook,
        'form': form,
        'now': now,
    }
    return render(request, 'edit_logpage.html', context)


@login_required()
def AboutPage(request):

      context = {}
      return render(request, 'about_page.html', context)

siwieapp/templates/about_page.html
{% extends 'index.html' %}
{% load static %}

        {% block title%}<title>AboutUs | MySiwie </title>{% endblock %}
      {% block content%}


<div class="main-container">
            <section class="text-center">
                <div class="container">
                    <div class="row">
                        <div class="col-md-10 col-lg-8">
                            <h1>About</h1>
                            <p class="lead">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus minima quisquam nihil, modi eum repellat saepe doloremque officia repudiandae quas a aliquam! Reprehenderit fugit excepturi beatae aut, pariatur voluptates aliquid.
                            </p>
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            <section class="switchable bg--secondary">
                <div class="container">
                    <div class="row justify-content-around">
                        <div class="col-md-6 col-lg-5">
                            <ul class="accordion accordion-2 accordion--oneopen" style="min-height: 268.9px;">
                                <li class="active">
                                    <div class="accordion__title">
                                        <span class="h5">Culture</span>
                                    </div>
                                    <div class="accordion__content">
                                        <p class="lead">
                                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam cupiditate quia provident iste repellendus neque sequi? Numquam ducimus maxime facilis repellendus consectetur porro, itaque rerum, accusamus suscipit aperiam, odit tenetur?
                                        </p>
                                    </div>
                                </li>
                                <li class="">
                                    <div class="accordion__title">
                                        <span class="h5">Benefits</span>
                                    </div>
                                    <div class="accordion__content">
                                        <p class="lead">
                                            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestias necessitatibus provident id rerum, reiciendis corrupti dolor esse alias illum deserunt ratione quaerat. Quasi molestiae cupiditate voluptatum commodi! Magnam, similique nobis!
                                        </p>
                                        <p class="lead">
                                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae voluptatem aliquam amet quis fuga placeat quos facilis tenetur, officiis illum excepturi dolores debitis quo quas tempore, numquam tempora minima illo.
                                        </p>
                                    </div>
                                </li>
                                <li>
                                    <div class="accordion__title">
                                        <span class="h5">Learning</span>
                                    </div>
                                    <div class="accordion__content">
                                        <p class="lead">
                                            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Corrupti alias tempora hic sapiente a ipsum expedita veritatis fuga. Quas, nobis repudiandae. Voluptatibus explicabo, in voluptas magnam provident hic maxime odio?
                                    </div>
                                </li>
                            </ul>
                            <!--end accordion-->
                        </div>
                        <div class="col-lg-6 col-md-6 switchable__text text-center">
                            <div class="video-cover border--round">
                                <div class="background-image-holder" style="background-color: rgba(0, 0, 0, 0); background-position: initial; background-repeat: repeat; background-attachment: scroll; background-image: url(&quot;siwieapp/img/recruitment-1.jpg&quot;); background-size: auto; background-origin: padding-box; background-clip: border-box; opacity: 1;">
                                    <img alt="image" src="{% static 'siwieapp/img/recruitment-1.jpg'%}">
                                </div>
                                <div class="video-play-icon"></div>
                                <iframe data-src="#" allowfullscreen="allowfullscreen"></iframe>
                            </div>
                            <!--end video cover-->
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>


          {% endblock%}

siwieapp/templates/career-single.html
{% extends 'index.html' %}
{% load static %}

        {% block title%}<title>Career Single | MySiwie </title>{% endblock %}
      {% block content%}
        <div class="main-container">
            <section class="space--sm">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1>{{intern.name_of_org}}</h1>
                            <h3>{{intern.course}}</h3>
                            <ol class="breadcrumbs">
                                <li>
                                    <a href="{% url 'index' %}">Home</a>
                                </li>
                                <li>
                                    <a href="#">placement</a>
                                </li>
                                <li>{{intern.name_of_org}}</li>

                            </ol>
                            <hr>
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            <section class="switchable">
                <div class="container">
                    <div class="row justify-content-around">
                        <div class="col-md-8 col-lg-7">
                            <h4>FAQ</h4>
                            <p>
                                Do they pay? <br>
                                {{intern.pay_status}}
                            </p>
                        </div>
                        <div class="col-md-4 col-lg-3">
                            <div class="text-block">
                                <h5>Address</h5>
                                <p>
                                    {{intern.address}}.
                                </p>
                                <p>
                                    {{intern.state}}.
                                </p>
                            </div>
                            <div class="text-block">
                                <h5>Tel</h5>
                                <p>
                                    {{intern.tel}}
                                </p>
                            </div>
                            <div class="text-block">
                                <h5>Description</h5>
                                <p>
                                    {{intern.tel}}
                                </p>
                            </div>
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            
          {% endblock%}

siwieapp/templates/edit_logpage.html
{% extends 'index.html' %}
{% load static %}

        {% block title%}<title>Add Log | MySiwie </title>{% endblock %}
      {% block content%}

     <div class="main-container">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="boxed boxed--lg boxed--border">

                            <h4>Date Published:  {{logbook.date_posted}}</h4>
                            <p>Edit your draft.</p>
                            <form method="post">
                              {%csrf_token%}
                                <div class="row">
                                    <div class="col-sm-12">
                                        {{form.as_p}}
                                    </div>
                                    <div class="col-sm-12">
                                        <button type="submit" class="btn btn--primary">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!--end of row-->
            </div>
</form>
          {% endblock%}

siwieapp/templates/log-single.html
{% extends 'index.html' %}
{% load static %}

        {% block title%}<title>Career Single | MySiwie </title>{% endblock %}
      {% block content%}
        <div class="main-container">
            <section class="space--sm">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">


                            <ol class="breadcrumbs">
                                <li>
                                    <a href="{% url 'index' %}">Home</a>
                                </li>
                                <li>
                                    <a href="#">My LogBook</a>
                                </li>
                                <h1>Week{{logbook.week}},Day {{logbook.day}}</h1>
                                <li><span>- {{logbook.date_posted}}</span></li>

                            </ol>
                            <hr>
                        </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            <section class="switchable">
                <div class="container">
                    <div class="row justify-content-around">
                        <div class="col-md-8 col-lg-7">
                            <h3>Details</h3><a href="{% url 'log_edit' logbook.id %}">Edit</a>

                                 <br>
                                {{logbook.log_details}}

                                <br>

                        </div>


                    </div>

                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>


          {% endblock%}

siwieapp/templates/profile-edit.html
{% extends 'index.html' %}
{% load static %}
{% block title%}<title>MyProfile | MySiwie </title>{% endblock%}
{% block content%}
      <div class="main-container">
            <section class="bg--secondary space--sm">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="boxed boxed--lg boxed--border">
                                <div class="text-block text-center">
                                    <img alt="avatar" src="{% static 'siwieapp/img/avatar-round-3.png' %}" class="image--sm">
                                    <span class="h5">{{request.user.first_name}} {{request.user.last_name}}</span>
                                    <span class="label">In Siwes</span>
                                </div>
                                <hr>
                                <div class="text-block">
                                    <ul class="menu-vertical">

                                        <li>
                                            <a href="{% url 'password_change' %}">Password</a>
                                        </li>
                                        <li>
                                            <a href="#" data-toggle-class=".account-tab:not(.hidden);hidden|#account-delete;hidden">Delete Account</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="boxed boxed--lg boxed--border">
                                <div id="account-profile" class="account-tab">
                                    <h4>Profile</h4>
                                    <form method="post" enctype="multipart/form-data">
                                        {%csrf_token%}
                                        <div class="row">
                                            <div class="col-md-12">
                                                <label>Firstname:</label>
                                                <input type="text" name="first_name" value="{{user.first_name}}" maxlength="30" id="id_first_name">
                                            </div>
                                             <div class="col-md-12">
                                                <label>Lastname:</label>
                                                <input type="text" name="last_name" value="{{user.last_name}}" maxlength="30" id="id_last_name">

                                            </div>
                                            <div class="col-md-12">
                                                <label>Email Address:</label>
                                                <input type="email" name="email" value="{{user.email}}" maxlength="30" id="id_email">
                                            </div>
                                           <div class="col-md-12">
                                                <label>Department:</label>
                                                <input type="text" name="course_of_interest" value="{{user.profile.course_of_interest}}" maxlength="225" id="id_course_of_interest">
                                            </div>
                                             <div class="col-md-12">
                                                <label>Placement Address:</label>
                                                <input type="text" name="placement_addr" value="{{user.profile.placement_addr}}" maxlength="225" id="id_placement_addr">
                                            </div>
                                             <div class="col-md-12">
                                                <label>Profile Picture:</label>
                                                <input type="file" name="profile_image" accept="image/*" id="id_profile_image"></p>

                                            </div>
                                            <div class="col-lg-3 col-md-4">
                                                <button type="submit" class="btn btn--primary type--uppercase">Save Profile</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>


                                <div id="account-delete" class="hidden account-tab">
                                    <h4>Delete Account</h4>
                                    <p>Permanently remove your account using the button below. Warning, this action is permanent.</p>
                                    <form>
                                        <button type="submit" class="btn bg--error type--uppercase">Delete Account</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
           {%endblock%}